import type { NodeSpec, GalleryItem } from './types';
import {
  Zap,
  FunctionSquare,
  FileTerminal,
  Shuffle,
  GitBranch,
  Filter,
  ArrowRight,
  Send,
  Database,
  Code2,
} from 'lucide-react';

export const NODE_REGISTRY: Record<string, NodeSpec> = {
  'trigger-http': {
    type: 'trigger-http',
    label: 'HTTP Request',
    category: 'Trigger',
    icon: Zap,
    description: 'Triggers workflow on an incoming HTTP request.',
    width: 250,
    inputs: [],
    outputs: [{ name: 'body', type: 'object' }, { name: 'headers', type: 'object' }],
  },
  'action-log': {
    type: 'action-log',
    label: 'Log to Console',
    category: 'Action',
    icon: FileTerminal,
    description: 'Logs the input data to the console.',
    width: 250,
    inputs: [{ name: 'data', type: 'any' }],
    outputs: [],
  },
  'action-function': {
    type: 'action-function',
    label: 'Function',
    category: 'Action',
    icon: FunctionSquare,
    description: 'Runs a JavaScript function.',
    width: 300,
    inputs: [
      { name: 'code', type: 'string', widget: 'textarea', label: 'JavaScript Code', placeholder: 'return { data: "Hello" };' }
    ],
    outputs: [{ name: 'result', type: 'any' }],
  },
  'action-send-email': {
    type: 'action-send-email',
    label: 'Send Email',
    category: 'Action',
    icon: Send,
    description: 'Sends an email using a configured SMTP service.',
    width: 250,
    inputs: [
      { name: 'to', type: 'string', widget: 'string', label: 'Recipient' }, 
      { name: 'subject', type: 'string', widget: 'string', label: 'Subject' }, 
      { name: 'body', type: 'string', widget: 'textarea', label: 'Body' }
    ],
    outputs: [{ name: 'status', type: 'string' }],
  },
  'action-db-query': {
    type: 'action-db-query',
    label: 'Database Query',
    category: 'Action',
    icon: Database,
    description: 'Executes a query against a connected database.',
    width: 280,
    inputs: [{ name: 'query', type: 'string', widget: 'textarea', label: 'SQL Query' }],
    outputs: [{ name: 'results', type: 'array' }],
  },
  'logic-router': {
    type: 'logic-router',
    label: 'Router',
    category: 'Logic',
    icon: Shuffle,
    description: 'Routes data to different branches based on conditions.',
    width: 250,
    inputs: [{ name: 'data', type: 'any' }],
    outputs: [{ name: 'match1', type: 'any' }, { name: 'match2', type: 'any' }, { name: 'default', type: 'any' }],
  },
  'logic-condition': {
    type: 'logic-condition',
    label: 'If/Else Branch',
    category: 'Logic',
    icon: GitBranch,
    description: 'Splits the workflow based on a true/false condition.',
    width: 250,
    inputs: [{ name: 'condition', type: 'boolean' }],
    outputs: [{ name: 'true', type: 'any' }, { name: 'false', type: 'any' }],
  },
  'logic-filter': {
    type: 'logic-filter',
    label: 'Filter Data',
    category: 'Logic',
    icon: Filter,
    description: 'Filters an array of items based on a condition.',
    width: 250,
    inputs: [{ name: 'array', type: 'array' }],
    outputs: [{ name: 'filteredArray', type: 'array' }],
  },
   'logic-code': {
    type: 'logic-code',
    label: 'Run Code',
    category: 'Logic',
    icon: Code2,
    description: 'Executes a custom JavaScript snippet.',
    width: 280,
    inputs: [{ name: 'input', type: 'any' }, { name: 'code', type: 'string', widget: 'textarea', label: 'Code' }],
    outputs: [{ name: 'output', type: 'any' }],
  },
  'output-response': {
    type: 'output-response',
    label: 'HTTP Response',
    category: 'Output',
    icon: ArrowRight,
    description: 'Sends a response back to the initial HTTP trigger.',
    width: 250,
    inputs: [{ name: 'body', type: 'object' }, { name: 'statusCode', type: 'number', widget: 'number', label: 'Status Code' }],
    outputs: [],
  },
};

export const MOCK_GALLERY_ITEMS: GalleryItem[] = [
    {
        id: '1',
        title: 'Automated Daily Report',
        author: 'dataguru',
        rating: 4.8,
        downloads: 1250,
        imageUrl: 'https://picsum.photos/seed/report/600/400',
        imageHint: 'report',
        tags: ['Reporting', 'Email', 'Database'],
        isNsfw: false,
        verificationStatus: 'verified'
    },
    {
        id: '2',
        title: 'Social Media Post Scheduler',
        author: 'socialsavvy',
        rating: 4.5,
        downloads: 890,
        imageUrl: 'https://picsum.photos/seed/social/600/400',
        imageHint: 'social',
        tags: ['Social', 'API', 'Scheduling'],
        isNsfw: false,
        verificationStatus: 'draft'
    },
    {
        id: '3',
        title: 'E-commerce Order Processing',
        author: 'shopmaster',
        rating: 4.9,
        downloads: 3400,
        imageUrl: 'https://picsum.photos/seed/ecommerce/600/400',
        imageHint: 'ecommerce',
        tags: ['E-commerce', 'Stripe', 'Twilio'],
        isNsfw: false,
        verificationStatus: 'verified'
    },
    {
        id: '4',
        title: 'AI Image Generation Pipeline',
        author: 'artifex',
        rating: 4.7,
        downloads: 2100,
        imageUrl: 'https://picsum.photos/seed/ai-art/600/400',
        imageHint: 'art',
        tags: ['AI', 'Image', 'API'],
        isNsfw: false,
        verificationStatus: 'verified'
    },
    {
        id: '5',
        title: 'NSFW Content Filter',
        author: 'guardian',
        rating: 4.2,
        downloads: 500,
        imageUrl: 'https://picsum.photos/seed/filter/600/400',
        imageHint: 'abstract',
        tags: ['Moderation', 'AI', 'Logic'],
        isNsfw: true,
        verificationStatus: 'draft'
    },
    {
        id: '6',
        title: 'Real-time Stock Alert',
        author: 'tradewiz',
        rating: 4.6,
        downloads: 1500,
        imageUrl: 'https://picsum.photos/seed/stock/600/400',
        imageHint: 'stock',
        tags: ['Finance', 'API', 'Alerts'],
        isNsfw: false,
        verificationStatus: 'draft'
    }
];

export const MOCK_RUN_HISTORY = [
    { id: 'run-1', workflowName: 'Automated Daily Report', status: 'Success', startedAt: '2023-10-27T10:00:00Z', duration: '15.2s' },
    { id: 'run-2', workflowName: 'Social Media Post Scheduler', status: 'Success', startedAt: '2023-10-27T09:45:00Z', duration: '5.1s' },
    { id: 'run-3', workflowName: 'E-commerce Order Processing', status: 'Failed', startedAt: '2023-10-27T09:30:00Z', duration: '2.5s' },
    { id: 'run-4', workflowName: 'Automated Daily Report', status: 'Success', startedAt: '2023-10-26T10:00:00Z', duration: '14.8s' },
    { id: 'run-5', workflowName: 'AI Image Generation Pipeline', status: 'Running', startedAt: '2023-10-27T10:05:00Z', duration: '...' },
    { id: 'run-6', workflowName: 'E-commerce Order Processing', status: 'Success', startedAt: '2023-10-26T09:30:00Z', duration: '2.2s' },
];
